// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module "vue" {
  export interface GlobalComponents {
    Breadcrumb: typeof import("./components/base-ui/breadcrumb.vue")["default"]
    DarkMode: typeof import("./components/base-ui/dark-mode.vue")["default"]
    ElAside: typeof import("element-plus/es")["ElAside"]
    ElAvatar: typeof import("element-plus/es")["ElAvatar"]
    ElBreadcrumb: typeof import("element-plus/es")["ElBreadcrumb"]
    ElBreadcrumbItem: typeof import("element-plus/es")["ElBreadcrumbItem"]
    ElButton: typeof import("element-plus/es")["ElButton"]
    ElCheckbox: typeof import("element-plus/es")["ElCheckbox"]
    ElContainer: typeof import("element-plus/es")["ElContainer"]
    ElDropdown: typeof import("element-plus/es")["ElDropdown"]
    ElDropdownItem: typeof import("element-plus/es")["ElDropdownItem"]
    ElDropdownMenu: typeof import("element-plus/es")["ElDropdownMenu"]
    ElForm: typeof import("element-plus/es")["ElForm"]
    ElFormItem: typeof import("element-plus/es")["ElFormItem"]
    ElHeader: typeof import("element-plus/es")["ElHeader"]
    ElInput: typeof import("element-plus/es")["ElInput"]
    ElLink: typeof import("element-plus/es")["ElLink"]
    ElMain: typeof import("element-plus/es")["ElMain"]
    ElMenu: typeof import("element-plus/es")["ElMenu"]
    ElMenuItem: typeof import("element-plus/es")["ElMenuItem"]
    ElSubMenu: typeof import("element-plus/es")["ElSubMenu"]
    ElTabPane: typeof import("element-plus/es")["ElTabPane"]
    ElTabs: typeof import("element-plus/es")["ElTabs"]
    FoldMenu: typeof import("./components/base-ui/fold-menu.vue")["default"]
    HelloWorld: typeof import("./components/HelloWorld.vue")["default"]
    IEpArrowDown: typeof import("~icons/ep/arrow-down")["default"]
    IEpAvatar: typeof import("~icons/ep/avatar")["default"]
    IEpExpand: typeof import("~icons/ep/expand")["default"]
    IEpFold: typeof import("~icons/ep/fold")["default"]
    IEpInfoFilled: typeof import("~icons/ep/info-filled")["default"]
    IEpIphone: typeof import("~icons/ep/iphone")["default"]
    IEpMonitor: typeof import("~icons/ep/monitor")["default"]
    IEpMoon: typeof import("~icons/ep/moon")["default"]
    IEpPlatform: typeof import("~icons/ep/platform")["default"]
    IEpSunny: typeof import("~icons/ep/sunny")["default"]
    IEpUserFilled: typeof import("~icons/ep/user-filled")["default"]
    NavHeader: typeof import("./components/nav-header/nav-header.vue")["default"]
    NavMenu: typeof import("./components/nav-menu/nav-menu.vue")["default"]
    UserInfo: typeof import("./components/base-ui/user-info.vue")["default"]
  }
}

export {}
